/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.view;

/**
 *
 * @author Alfian Hidayat
 */
public class Pengembalian extends javax.swing.JPanel {

    /**
     * Creates new form Pengembalian
     */
    public Pengembalian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTglKembali = new javax.swing.JLabel();
        txtTglKembali = new javax.swing.JPasswordField();
        txtDenda = new javax.swing.JPasswordField();
        lblDenda = new javax.swing.JLabel();
        btnCekID = new javax.swing.JButton();
        lblTerlambat = new javax.swing.JLabel();
        txtTerlambat = new javax.swing.JPasswordField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        lblIDFaktur = new javax.swing.JLabel();
        lblBatasTgl = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        txtIDFaktur = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblTglMulai = new javax.swing.JLabel();
        lblIDKembali = new javax.swing.JLabel();
        txtTglMulai = new javax.swing.JTextField();
        txtIDKembali = new javax.swing.JTextField();
        txtNamaMember = new javax.swing.JTextField();
        lblNamaMember = new javax.swing.JLabel();
        txtBatasTgl = new javax.swing.JPasswordField();

        lblTglKembali.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblTglKembali.setText("Tanggal Kembali");

        txtTglKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglKembaliActionPerformed(evt);
            }
        });

        txtDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDendaActionPerformed(evt);
            }
        });

        lblDenda.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblDenda.setText("Denda");

        btnCekID.setText("Cek ID Sewa");

        lblTerlambat.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblTerlambat.setText("Terlambat");

        txtTerlambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerlambatActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kendaraan "));

        jLabel1.setText("ID Kendaraan");

        jLabel2.setText("Merek Kendaraan");

        jLabel3.setText("Nomor Polisi");

        jLabel4.setText("Harga Sewa");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblIDFaktur.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblIDFaktur.setText("ID Faktur");

        lblBatasTgl.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblBatasTgl.setText("Batas Tanggal Kembali");

        lblAlamat.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblAlamat.setText("Alamat");

        txtIDFaktur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFakturFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFakturFocusLost(evt);
            }
        });
        txtIDFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDFakturActionPerformed(evt);
            }
        });

        txtAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAlamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlamatFocusLost(evt);
            }
        });
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        btnSave.setText("Simpan Transaksi");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTglMulai.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblTglMulai.setText("Tanggal Mulai");

        lblIDKembali.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblIDKembali.setText("ID Kembali");

        txtTglMulai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTglMulaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTglMulaiFocusLost(evt);
            }
        });
        txtTglMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglMulaiActionPerformed(evt);
            }
        });

        txtIDKembali.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDKembaliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDKembaliFocusLost(evt);
            }
        });
        txtIDKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDKembaliActionPerformed(evt);
            }
        });

        txtNamaMember.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaMemberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaMemberFocusLost(evt);
            }
        });
        txtNamaMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMemberActionPerformed(evt);
            }
        });

        lblNamaMember.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        lblNamaMember.setText("Member");

        txtBatasTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatasTglActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBatasTgl)
                                        .addComponent(lblTglKembali)
                                        .addComponent(lblDenda)
                                        .addComponent(lblTerlambat))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBatasTgl)
                                        .addComponent(txtTglKembali)
                                        .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTerlambat)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIDFaktur)
                                        .addComponent(lblIDKembali)
                                        .addComponent(lblNamaMember)
                                        .addComponent(lblAlamat)
                                        .addComponent(lblTglMulai))
                                    .addGap(77, 77, 77)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtIDKembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                                .addComponent(txtIDFaktur, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnCekID))))))
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTglMulai)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIDFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCekID)
                                .addComponent(lblIDFaktur))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIDKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIDKembali))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNamaMember))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAlamat))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBatasTgl)
                        .addComponent(txtBatasTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTglKembali)
                        .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTerlambat)
                        .addComponent(txtTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDenda)
                        .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnSave)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTglKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglKembaliActionPerformed

    private void txtDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDendaActionPerformed

    private void txtTerlambatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerlambatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerlambatActionPerformed

    private void txtIDFakturFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFakturFocusGained

    }//GEN-LAST:event_txtIDFakturFocusGained

    private void txtIDFakturFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFakturFocusLost

    }//GEN-LAST:event_txtIDFakturFocusLost

    private void txtIDFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDFakturActionPerformed

    }//GEN-LAST:event_txtIDFakturActionPerformed

    private void txtAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlamatFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatFocusGained

    private void txtAlamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlamatFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatFocusLost

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtTglMulaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTglMulaiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglMulaiFocusGained

    private void txtTglMulaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTglMulaiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglMulaiFocusLost

    private void txtTglMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglMulaiActionPerformed

    private void txtIDKembaliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDKembaliFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKembaliFocusGained

    private void txtIDKembaliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDKembaliFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKembaliFocusLost

    private void txtIDKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKembaliActionPerformed

    private void txtNamaMemberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaMemberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMemberFocusGained

    private void txtNamaMemberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaMemberFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMemberFocusLost

    private void txtNamaMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMemberActionPerformed

    private void txtBatasTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatasTglActionPerformed

    }//GEN-LAST:event_txtBatasTglActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekID;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblBatasTgl;
    private javax.swing.JLabel lblDenda;
    private javax.swing.JLabel lblIDFaktur;
    private javax.swing.JLabel lblIDKembali;
    private javax.swing.JLabel lblNamaMember;
    private javax.swing.JLabel lblTerlambat;
    private javax.swing.JLabel lblTglKembali;
    private javax.swing.JLabel lblTglMulai;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JPasswordField txtBatasTgl;
    private javax.swing.JPasswordField txtDenda;
    private javax.swing.JTextField txtIDFaktur;
    private javax.swing.JTextField txtIDKembali;
    private javax.swing.JTextField txtNamaMember;
    private javax.swing.JPasswordField txtTerlambat;
    private javax.swing.JPasswordField txtTglKembali;
    private javax.swing.JTextField txtTglMulai;
    // End of variables declaration//GEN-END:variables
}
